---

- name: "Server Configuration" 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  environment: 
    IMAGETAG: "{{ IMAGETAG }}"

  pre_tasks:  
    - name: Tagname
      raw: echo "Using tagname {{ IMAGETAG }}"

    - name: Task name
      stat:
        path: ~/HelloWorld
      register: helloWorldDir

    - name: Git checkout
      raw: git clone https://github.com/zutils/HelloWorld.git
      when: not helloWorldDir.stat.exists

    - name: Git checkout
      raw: cd HelloWorld && git pull
      when: helloWorldDir.stat.exists

  roles:
    - configure-server