---

- name: "Server Configuration" 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:  
    - name: Git checkout
        raw: git clone https://github.com/zutils/HelloWorld.git
      #ansible.builtin.git:
      #  repo: 'https://github.com/zutils/HelloWorld.git'
      #  dest: ~/

  roles:
    - configure-server