--- 
- name: "Install Docker"
  raw: sh ./HelloWorld/.circleci/files/install_docker.sh

- name: "Set Docker Permissions"
  raw: sh ./HelloWorld/.circleci/files/set_docker_permissions.sh

- name: "Install Minikube"
  raw: sh ./HelloWorld/.circleci/files/install_minikube.sh

- name: "Patching Image Name"
  raw: cat ~/HelloWorld/.circleci/files/deployment.yml | sed -s "s|IMAGETAG|{{ IMAGETAG }}|g" > /tmp/modified_deployment.yml

- name: "Roll Update"
  environment:
    IMAGETAG: "{{ IMAGETAG }}"
  raw: sh ./HelloWorld/.circleci/files/roll_update.sh