Description: >
  Hello_world_server backend. Access on port 80

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: backend-group-hello_world_server
      GroupDescription: Allow port 22 and port 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.small # Not free tier, but need t3 for 2 vcpus and 2gb mem
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udacity 
      ImageId: ami-07dd19a7900a1f049
      Tags:
        - Key: Name
          Value: backend-hello_world_server

  ElasticIpAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties: 
      AllocationId: eipalloc-0c6edaf2400001884 # Attach to a permanent elastic ip
      InstanceId: !Ref EC2Instance
    