apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-server
  template:
    metadata:
      labels:
        app: hello-world-server
    spec:
      containers:
      - name: hello-world-server
        image: jzypo/udacity:IMAGETAG
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
